### PR TITLE
Improve handling of errors in SETSM product packaging scripts

### PR DESCRIPTION
**Pull request by ehusby**
- Needs more testing 
- Currently only applied improvements to mosaic file packaging
- Should apply improvements to strip file packaging as well

### CODE REVIEW

**Review by clairecporter — APPROVED** [review]
This looks good.  I did not test it since I assume you did so when you packaged the ArcticDEM tiles?

**Comment by ehusby** [comment]
I did test run the packager using these changes, but that didn't get to test the failure cases. I'll test again, purposely raising some exceptions in the code to make sure the error catches work properly.

**Comment by clairecporter** [comment]
Strip packaging changes added.  Not sure how to test these failure conditions.  But everything works in the happy path.

**Comment by clairecporter** [comment]
I'm fine with this as is.  Unless you feel we need to do more careful testing, I am comfortable rolling it in.

**Comment by ehusby** [comment]
Agreed! I'll merge it in now.

**Pull request merged**
